version: '3.7'
services:
    dbpg:
        build: 
          context: .
          dockerfile: Dockerfile-db
        restart: always
        environment:
          - POSTGRES_USER=postgres
          - POSTGRES_PASSWORD=postgres
        ports:
          - 5432:5432
        volumes: 
          - ./scripts/seed.sql:/docker-entrypoint-initdb.d/seed.sql          
    web-node:
        build: .
        restart: always
        ports:
          - 8080:8080
        env_file:
          - .env  
        depends_on:
          - dbpg
